### ISSUE TITLE
Lineas de negocio, no son claras - retirar las lineas que no estan activas

### ISSUE THREAD

**Issue by cahenaof** [TheSignLab/ConceptLab_20180207_TS_Imi#15]
![image](https://user-images.githubusercontent.com/37115318/37042357-44b9030e-212c-11e8-8f18-4cab229eb6d5.png)

Luego de revisar la experiencia de usuario, las personas desconocen las lineas de negocia, se propone ocultar los elementos inactivos.

**Comment by TheSignLab** [comment]
@cahenaof  Cuales podrían ir entonces? Manifiesto, Creative y Equipo y cuales mas?

**Comment by cahenaof** [comment]
George, creo conveniente conversar con Male y Vane para determinar los que deben ir, creo al igual que Usted Manifiesto / Creative / Equipo.

**Comment by TheSignLab** [comment]
@cahenaof Hable con Vanesa y me dijo que poner un error 404 ( Algo como pagina en construcción) Para los links caídos. No se ud que opine?.

**Comment by TheSignLab** [comment]
Cierro con la solución aportada en los cambios de código del menu
