### ISSUE TITLE
Link de redes que no me saquen de la pag. 

### ISSUE THREAD

**Issue by malejandram** [TheSignLab/ConceptLab_20180207_TS_Imi#24]
![image](https://user-images.githubusercontent.com/37300098/37289459-b6408fb0-25d7-11e8-9459-9c13a53ae8e4.png)

Cuando hago click alguna red me saca de la pagina, es mejor que se abra una nueva pestaña.

**Comment by TheSignLab** [comment]
Solucionando con window.open( url, "_blank"). 
Requiere editar cada archivo footer/script.js de cada versión (Home/Desk, Home/Mobile, Home/Tablet, etc).
