### ISSUE TITLE
Galería de imágenes / proeyctos en móvil 

### ISSUE THREAD

**Issue by malejandram** [TheSignLab/ConceptLab_20180207_TS_Imi#31]
![image](https://user-images.githubusercontent.com/37300098/37290765-22683564-25db-11e8-9207-1ecd46e00f78.png)

Ajustar para que las flechas se vean y se vea centrado verticalmente las fotos en grande.

**Comment by TheSignLab** [comment]
Solucionado usando imágenes no al height:80vh sino al heigh:60vh.
