### ISSUE TITLE
Poner botones en color blanco del intro CTS

### ISSUE THREAD

**Issue by VanessaChavarro** [TheSignLab/ConceptLab_20180207_TS_Imi#40]
Estos botones se están perdiendo

![image](https://user-images.githubusercontent.com/37372941/37406950-7eb48390-2766-11e8-9044-082a65ee93b0.png)

**Comment by TheSignLab** [comment]
En S0.ScrollUp -> Navbar.class == "nav-dark". 
Entonces mejorar a  
S0.ScrollUp -> Navbar.class == "nav-light".
